### ISSUE TITLE
Crash on El Capitan

### ISSUE THREAD

**Issue by diekhans** [jrnewell/disk-arbitration-agent#1]
Occurs frequently.  Happy to help debug with some guidance (not a mac programmer).

thanks so much for this,,

[DiskArbitrationAgent_2016-03-20-083325_osprey.crash.txt](https://github.com/jrnewell/disk-arbitration-agent/files/181492/DiskArbitrationAgent_2016-03-20-083325_osprey.crash.txt)

**Comment by diekhans** [comment]
Discovered this is caused by
      taskgated[142]: killed DiskArbitrationAgent-5555494479de5116cada3e5a8147a51044733e35[pid 10565] because its use of the com.apple.private.notificationcenter-system entitlement is not allowed (error code -67050)
      com.apple.xpc.launchd[1](com.apple.DiskArbitrationAgent[10565]): Binary is improperly signed.

which caused launchd/ReportCrash mad loop.

**Comment by GerardGarcia** [comment]
Same here

**Comment by jrnewell** [comment]
Yeah sorry, I was upgrading my desktop and had some issues with it so I haven't had access to my hackintosh.  Hopefully, I will be able to look at this next week.

**Comment by jrnewell** [comment]
You might be able to fix this by code signing the binary with no identity:

```
codesign -fs - DiskArbitrationAgent
```

It also could be due to SIP.   I have it disabled on my machine so I never really tested if it works with it turn on.

**Comment by jrnewell** [comment]
Sorry, I lost track of this.  I am fairly certain this was the cause.  I tried removing the signature from the binary (using the command above) and uploaded a new 10.11 release.
