### ISSUE TITLE
can you make it work for USB disks as well?

### ISSUE THREAD

**Issue by tessus** [jrnewell/disk-arbitration-agent#2]
Whenever I plugin an encrypted USB disk or stick I get the same annoying message.

Is there any chance you can create an option (e.g. -u) for usb drives as well? Shouldn't be too complicated. Hint: `kIOPropertyPhysicalInterconnectTypeUSB`

Also, I think there's a typo in the [usage info](https://github.com/jrnewell/disk-arbitration-agent/commit/0e493f37e0464cd271b9332aa16f5d7ec9c3dd01#diff-bdf180f63e4b82a9a247412c2bb8311eR45). I think it should be

```
fprintf( stderr, "\t-s\tdisable messages for unreadble SATA disks\n" );
```

instead.

**Comment by jrnewell** [comment]
Thanks for the help.  I added your suggestion: `-u` option for ignoring USB drives too.  It is in the releases pages: https://github.com/jrnewell/disk-arbitration-agent/releases/tag/10.10_2.

**Comment by tessus** [comment]
awesome, thank you. I would have added it myself, but I cannot compile the code as you can see in #3.
