### ISSUE TITLE
compile error: no known class method for selector '_centerForIdentifier:type:'

### ISSUE THREAD

**Issue by tessus** [jrnewell/disk-arbitration-agent#3]
I get the following error, when I try to compile the code:

```
disk-arbitration-agent/DiskArbitrationAgent/DADialog.m:54:41: error: no known class method for selector '_centerForIdentifier:type:'
    center = [ NSUserNotificationCenter _centerForIdentifier: @_kDAAgentName type: 0x2 ];
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I'm using Xcode 7.3.1 on Mac OSX 10.11.6. I copied the private header files as described in the README. I also tried compiling the new DiskArbitration-277. Same problem. (How can Apple make source code available that you can't compile? Makes no sense to me.)

How were you able to compile it?

**Comment by jrnewell** [comment]
Yeah I just ended up using the private headers directly in a special directory instead of copying them.  I updated the instructions to reflect that.  Let me know if that helps you at all.  I am using Xcode 7.3.1 too.

**Comment by tessus** [comment]
Unfortunately this changes nothing for me. I still get the same error. Also, I've already copied the files into the SDK directory as mentioned above. Using an additional include path or copying the files should yield the same result.
So I believe you might have missed a few private header files, which are present in your sdk path, but not in this project.

**Comment by jrnewell** [comment]
It should be in `disk-arbitration-agent/PrivateHeaders/Foundation/NSUserNotification.h` line 119 

``` objective-c
+ (id)_centerForIdentifier:(id)arg1 type:(unsigned long long)arg2;
```

However, it looks it is picking up the non-edited version in your case `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSUserNotification.h`, which doesn't have that line.

This would be a lot easier if Apple just included everything!

**Comment by tessus** [comment]
yep, you're right. I've patched (added that line to) my `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Versions/C/Headers/NSUserNotification.h` and I was able to compile it. 
I didn't copy the `NSUserNotification.h` file from the private headers directory, because I already had one in the SDK which was newer, thus didn't want to remove/replace newer code.

This is really very strange. I still do not understand how Apple can release code on http://opensource.apple.com/ that does not compile. Why do they release it in the first place? Makes no sense to me.

**Comment by tessus** [comment]
Maybe you could add the info to the README that if you didn't want to overwrite your `NSUserNotification.h`, you should add the following line to it:

```
+ (id)_centerForIdentifier:(id)arg1 type:(unsigned long long)arg2;
```

The problem is that all other files do not exist in the SDK, but this one does, which means you either overwrite it with an older version or use an older file during compilation (because of your search path change).

Oh, and another info would be good: you have to reboot the machine, because OSX caches the plist files. This means you use the new version of the file, but without the parameter.

**Comment by tessus** [comment]
It's also worth mentioning that Integrity Protection has to be turned off to replace the necessary files.

**Comment by jrnewell** [comment]
OK.  I added your suggestions to the README.  Let me know if you notice anything else missing.

**Comment by tessus** [comment]
No, everything looks good. Thank you.
